pub(crate) const DEFAULT_TOP_K: usize = 5;
pub(crate) const DEFAULT_BUDGET_TOKENS: usize = 20_000;
pub(crate) const DEFAULT_MAX_PAGES: usize = 2048;
pub(crate) const DEFAULT_CRAWL_CONCURRENCY: usize = 16;
pub(crate) const EMBEDDING_BATCH_SIZE: usize = 64;
pub(crate) const RRF_K: f64 = 60.0;
pub(crate) const LLMS_TXT_SOURCE_PRIOR_SCORE: f64 = 0.002;
pub(crate) const AGENTS_BLOCK_START: &str = "<!-- ctx:start -->";
pub(crate) const AGENTS_BLOCK_END: &str = "<!-- ctx:end -->";
